### ISSUE TITLE
Unknown Mod Conflict Causing Strange Inventory Screen Background Render Crash

### ISSUE THREAD

**Issue by Rogenar** [milkev/Milkevs-Essentials#3]
In milkevsessentials-1.9.2b version, it causes crashes in the game.
[latest.log](https://github.com/milkev/Milkevs-Essentials/files/12130501/latest.log)
[rei.log](https://github.com/milkev/Milkevs-Essentials/files/12130507/rei.log)
[crash-2023-07-21_19.15.52-client.txt](https://github.com/milkev/Milkevs-Essentials/files/12130516/crash-2023-07-21_19.15.52-client.txt)
[rei-issues.log](https://github.com/milkev/Milkevs-Essentials/files/12130517/rei-issues.log)

**Comment by milkev** [comment]
The crash log seems related to screen rendering, something my mod doesnt touch at all. When was this crash occuring?

**Comment by Rogenar** [comment]
I downloaded the mod you just updated 1 hour ago and created a new world. The game crashed when I opened the inventory, but I didn't encounter the same problem when I removed your mod and created the world again.

**Comment by milkev** [comment]
Weird. Its definitely a mod conflict, since I'm not getting any crashes with just Milkevs Essentials 1.9.2b & its dependencies installed. The error log points at REI & Architectury, but testing with the latest versions of both installed still doesnt give me a crash. If you can find what the other mod is, then I can see if I'm able to fix the issue

**Comment by milkev** [comment]
i'll re open if anyone is able to reproduce this
