### ISSUE TITLE
[1.20] Incompatibilty with Sinytra Connector

### ISSUE THREAD

**Issue by aking4125** [milkev/Milkevs-Essentials#5]
Most likely nothing that can be done here but reporting it here to cross reference the issues:

Upon using [Sinytra Connector](https://legacy.curseforge.com/minecraft/mc-mods/sinytra-connector), [Forgified Fabric API](https://legacy.curseforge.com/minecraft/mc-mods/forgified-fabric-api), [Trinkets (Fabric)](https://legacy.curseforge.com/minecraft/mc-mods/trinkets), [Cloth Config API (Fabric)](https://legacy.curseforge.com/minecraft/mc-mods/cloth-config) and [this mod](https://legacy.curseforge.com/minecraft/mc-mods/milkevs-essentials/files/4656040). 

The client crashes but no crash report is created: 

Debug.log: https://pastebin.com/pHNqt3As
Prism Launcher Log: https://pastebin.com/6cd35zpk

Removing only Milkev Essentials allows the client to launch normally even with Trinkets and Cloth Config Api.

https://github.com/Sinytra/Connector/issues/133

**Comment by milkev** [comment]
Seems to be due to Sinytra being incompatable with Reach Entity Attributes
https://github.com/Sinytra/Connector/discussions/12#:~:text=Reach%20Entity%20Attributes,Forge%20attribute%20modifiers

Currently unsure if I can do anything about this, in the meantime here is a version of Milkevs Essentials that has no REA implementations. This does have Extendo Grips disabled, fair warning to anyone wanting to use this.
[milkevsessentials-1.9.2b-NoExtendoGrips.zip](https://github.com/milkev/Milkevs-Essentials/files/12454811/milkevsessentials-1.9.2b-NoExtendoGrips.zip)

**Comment by milkev** [comment]
according to [https://github.com/Sinytra/Connector/issues/133#issuecomment-1722544238](https://github.com/Sinytra/Connector/issues/133#issuecomment-1722544238) this should be resolved, awaiting testing to make sure
